# Prod Configuration

roi:
  host: "dwcs-roi-sys-api.us-e2.cloudhub.io"
  basePath: "api" 
  acknowledgment:
    path: "acknowledgment"
  customers:
    path: "/customers/batch"
  sales_order_headers:
    path: "/sales-order-headers/batch"
  sales_order_details:
    path: "/sales-order-details/batch"
  items:
    path: "/items/batch"
  
sf:
  host: "dwcs-salesforce-sys-api.us-e2.cloudhub.io"
  path: "bulkUpsert"
  basePath: "api" 
  
sfState:
  host: "deepwater.my.salesforce.com"
  oAuthToken: "/services/oauth2/token" 
  client_id: "3MVG9PzgLRblCnyVDJHHSpK4oHoxMyoJ3.iSCdy7fbiKvxkVASJEvmWJWFQqsVLlZHXxinZsiZaSEmYLrFpKf"
  client_secret: "1B1FEDD5E002743F373BCBB8516A04C4D3B06AB91CEEBC078B2B7AD79493A782"
  
acknowledgment:
  responseTimeout: "1000000"
  
salesforce:
  authorizationUrl: "https://deepwater.my.salesforce.com/services/Soap/u/56.0"