# Prod Configuration

#API Id
api:
  id: "19565975"

# Project Insights
projectInsights:
  host: "deepwater.projectinsight.net"
  basePath: "/api"
  Time_Entry__c:
    path: "/time-entry/search"
  Expense_Entry__c:
    path: "/expense-entry/search"
  User:
    path: "/user/by-email-address"
  apiToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNzAzMDUsImV4cCI6MjE3NzM4ODAwMCwic3ViIjoiZWEwNDUxMmUtNmMzYi00NjFkLWE2MTktN2VjM2JiYmFkZTRiIn0.WwC-qxI7CgywhDN5XcER8YTwDOG4c04VlUgJn4cRxAafBEBs3Dw6WLP-JcBmmOlWHiHafXQWJWDXNT0Uajpc-A"  

sf:
  expirationInterval: "1"
  entryTtl: "58"
  
sfState:
  host: "deepwater.my.salesforce.com"
  oAuthToken: "/services/oauth2/token" 
  client_id: "3MVG9PzgLRblCnyVDJHHSpK4oHoxMyoJ3.iSCdy7fbiKvxkVASJEvmWJWFQqsVLlZHXxinZsiZaSEmYLrFpKf"
  client_secret: "1B1FEDD5E002743F373BCBB8516A04C4D3B06AB91CEEBC078B2B7AD79493A782"
  
acknowledgment:
  responseTimeout: "1000000"  

salesforce:
  authorizationUrl: "https://deepwater.my.salesforce.com/services/Soap/u/56.0"
  
sfVar:
  lineEnding: "LF"
  contentType: "CSV"
  operation: "upsert"
  columnDelimiter: "PIPE"
  externalId: "Id__c"
  
response:
  timeout: "600000"