# Prod Configuration
  
# Project Insights
projectInsights:
  host: "deepwater.projectinsight.net"
  basePath: "/api"
  Time_Entry__c:
    path: "/time-entry/search"
  Expense_Entry__c:
    path: "/expense-entry/search"
  apiToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkyMTQxMTgsImV4cCI6MTczNTYyNDgwMCwic3ViIjoiY2VjOTcyNjYtN2Q0Yy00ZDY5LWJlOTEtYmYyY2FhZDlhNDdiIn0.ndhrlffvAIgAxdd4tEsaZq3DC_amnHfeVQ3H2wftiD62i-9ZOYTCs6GmEEDY2NYYTIqME4rmYyfe7gg8TCL3pA"  

sf:
  expirationInterval: "1"
  entryTtl: "58"
  
sfState:
  host: "deepwater.my.salesforce.com"
  oAuthToken: "/services/oauth2/token" 
  client_id: "3MVG9PzgLRblCnyVDJHHSpK4oHoxMyoJ3.iSCdy7fbiKvxkVASJEvmWJWFQqsVLlZHXxinZsiZaSEmYLrFpKf"
  client_secret: "1B1FEDD5E002743F373BCBB8516A04C4D3B06AB91CEEBC078B2B7AD79493A782"
  
acknowledgment:
  responseTimeout: "1000000"  

salesforce:
  authorizationUrl: "https://deepwater.my.salesforce.com/services/Soap/u/56.0"
  
sfVar:
  lineEnding: "CRLF"
  contentType: "CSV"
  operation: "upsert"
  columnDelimiter: "PIPE"
  externalId: "Id__c"
  
response:
  timeout: "600000"