# Prod Secure Credentials

sf:
  client_id: "![7MkMQIxx8hsg3kdswRBQAUrYtC/jNVJjloLN4r6GW7sEFeYjOO0kHQ==]"
  client_secret: "![6d3uivOP3dOa3yrLAGs+wQvm0Ujxog7O0q2mYWgYI0icFAeJXptrjQ==]"
  
salesforce:
  username: "![h9yoBwoSUfPDowSh0GsYbCQ0ZPf0eWkmKMxVF3PBnVQ=]"
  password: "![+A7+fQ2v0pSiaEjEYx11M7AL0i/G7x7/]"
  securityToken: "![c2tPz2Y9+AN9IXTzZ1Oa/zVGy8jTGO85MK4R/vxFTBY=]"
  
tls:
  password: "![aMEK+W3FUy/hCTzdarg7ig==]"