# Local Secure Credentials

sf:
  client_id: "![7MkMQIxx8hsg3kdswRBQAUrYtC/jNVJjloLN4r6GW7sEFeYjOO0kHQ==]"
  client_secret: "![6d3uivOP3dOa3yrLAGs+wQvm0Ujxog7O0q2mYWgYI0icFAeJXptrjQ==]"
  
salesforce:
  username: "![ADWRQMAL1hLMKr0c1OqzgxLtYFebDHot+YsBiJY9yDDwnM73Ne0u3A==]"
  password: "![aMEK+W3FUy/dJgiJ4qDI7A==]"
  securityToken: "![ZaI68aayyyWQTXnCJaGSicnetfhzK3xmIzattUtdJ9M=]"