# Prod Secure Credentials

sf:
  client_id: "![7MkMQIxx8hsg3kdswRBQAUrYtC/jNVJjloLN4r6GW7sEFeYjOO0kHQ==]"
  client_secret: "![6d3uivOP3dOa3yrLAGs+wQvm0Ujxog7O0q2mYWgYI0icFAeJXptrjQ==]"
  
salesforce:
  username: "![h9yoBwoSUfPDowSh0GsYbCQ0ZPf0eWkmKMxVF3PBnVQ=]"
  password: "![04BDEostTvqhr388MrU12Q==]"
  securityToken: "![kgwbsEAvtygfjReJxZaMJgAB/pA70kRy7Mmk5W2L48g=]"
  
tls:
  password: "![aMEK+W3FUy/hCTzdarg7ig==]"